# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sander Geraedts
job: Front-end Developer
company: Sogeti
company_url: https://www.sogeti.nl/
email: sander.geraedts@sogeti.com
description: >-
  Sander is een creatieve en analytische Front-end Developer met kennis van
  zowel web als mobile development. Sander heeft altijd gewerkt aan web projecten
  voor MKB-ondernemingen, voornamelijk binnen de innovatie-sector. Dit deed hij
  als Lead Developer van een team van zowel Front- als Backend developers. Sander
  heeft tijdens zijn werk en studie geleerd om snel te schakelen tussen taken en
  het overzicht over het grote plaatje te bewaren.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
linkedIn_url: https://www.linkedin.com/in/sander-geraedts/
github_username:  SanderGeraedts
sass:
  style: compressed
  sass_dir: _sass

# Build settings
plugins:
  - jekyll-feed

collections:
  portfolios:
    output: true
  blogs:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
